version: '3.7'

# Currently, the server is now hosted on Heroku, so environment variables about Postgres and Redis are actually not needed.
# I added them just for practice.

services:
  # Backend
  project_backend:
    container_name: project_backend
    build: ./
    command: npm start
    working_dir: /usr/src/project_backend
    environment:
      POSTGRES_URL: postgres://lcizpawvwlafuu:ba2ecfe1f6bb6059cce271b2e8358f16b0c4c723fa1e09a9cdc8c34b93d6ad78@ec2-174-129-242-183.compute-1.amazonaws.com:5432/daindnaflf7dmf
      REDIS_URL: redis://redis:6379
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/project_backend
      - /usr/src/project_backend/node_modules

  # Postgres
  postgres:
    build: ./postgres
    environment:
      POSTGRES_USER: Jin
      POSTGRES_PASSWORD: welcome
      POSTGRES_DB: project_backend_docker
      POSTGRES_HOST: postgres
    ports:
      - "5432:5432"
  
  # Redis
  redis:
    image: redis
    ports:
      - "6379:6379"